/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { ICurve, ICurveInterface } from "../../Interfaces/ICurve";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_totalSupply",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_poolBalance",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_reserveRatio",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "calculatePurchaseReturn",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_totalSupply",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_poolBalance",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_reserveRatio",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "calculateSaleReturn",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class ICurve__factory {
  static readonly abi = _abi;
  static createInterface(): ICurveInterface {
    return new Interface(_abi) as ICurveInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ICurve {
    return new Contract(address, _abi, runner) as unknown as ICurve;
  }
}
