/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  Nil,
  NilInterface,
} from "../../../../../@nilfoundation/smart-contracts/contracts/Nil.sol/Nil";

const _abi = [
  {
    inputs: [],
    name: "ASYNC_REQUEST_MIN_GAS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "FORWARD_NONE",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "FORWARD_PERCENTAGE",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "FORWARD_REMAINING",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "FORWARD_VALUE",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "IS_INTERNAL_MESSAGE",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "IS_RESPONSE_MESSAGE",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "LOG",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MANAGE_CURRENCY",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "VERIFY_SIGNATURE",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x610309610053600b82828239805160001a607314610046577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106100a85760003560e01c8063a167fd5f11610070578063a167fd5f14610143578063cbb1c30a14610161578063cc8a10e31461017f578063d2ec13b21461019d578063df09b8eb146101bb576100a8565b806305605778146100ad5780631816a5e1146100cb57806342e6d4d7146100e95780637f0a921b146101075780639bc465a014610125575b600080fd5b6100b56101d9565b6040516100c2919061024d565b60405180910390f35b6100d36101de565b6040516100e0919061024d565b60405180910390f35b6100f16101e3565b6040516100fe9190610284565b60405180910390f35b61010f6101e8565b60405161011c919061024d565b60405180910390f35b61012d6101ed565b60405161013a9190610284565b60405180910390f35b61014b6101f2565b604051610158919061024d565b60405180910390f35b6101696101f7565b60405161017691906102b8565b60405180910390f35b6101876101fd565b604051610194919061024d565b60405180910390f35b6101a5610202565b6040516101b29190610284565b60405180910390f35b6101c3610207565b6040516101d09190610284565b60405180910390f35b60d081565b60da81565b600081565b60ff81565b600181565b60fe81565b61c35081565b60d981565b600281565b600381565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006102378261020c565b9050919050565b6102478161022c565b82525050565b6000602082019050610262600083018461023e565b92915050565b600060ff82169050919050565b61027e81610268565b82525050565b60006020820190506102996000830184610275565b92915050565b6000819050919050565b6102b28161029f565b82525050565b60006020820190506102cd60008301846102a9565b9291505056fea26469706673582212207536b0d20dd811086cf978dd87ba5ed8da20ebdc0b28c6cd9f7b681a39dc262f64736f6c63430008180033";

type NilConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: NilConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Nil__factory extends ContractFactory {
  constructor(...args: NilConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Nil & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Nil__factory {
    return super.connect(runner) as Nil__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): NilInterface {
    return new Interface(_abi) as NilInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Nil {
    return new Contract(address, _abi, runner) as unknown as Nil;
  }
}
