/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  Nil,
  NilInterface,
} from "../../../../../@nilfoundation/smart-contracts/contracts/Nil.sol/Nil";

const _abi = [
  {
    inputs: [],
    name: "ASYNC_REQUEST_MIN_GAS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "FORWARD_NONE",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "FORWARD_PERCENTAGE",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "FORWARD_REMAINING",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "FORWARD_VALUE",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "IS_INTERNAL_MESSAGE",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MANAGE_CURRENCY",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "VERIFY_SIGNATURE",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6102ad610053600b82828239805160001a607314610046577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106100925760003560e01c8063a167fd5f11610065578063a167fd5f1461010f578063cbb1c30a1461012d578063d2ec13b21461014b578063df09b8eb1461016957610092565b8063056057781461009757806342e6d4d7146100b55780637f0a921b146100d35780639bc465a0146100f1575b600080fd5b61009f610187565b6040516100ac91906101f1565b60405180910390f35b6100bd61018c565b6040516100ca9190610228565b60405180910390f35b6100db610191565b6040516100e891906101f1565b60405180910390f35b6100f9610196565b6040516101069190610228565b60405180910390f35b61011761019b565b60405161012491906101f1565b60405180910390f35b6101356101a0565b604051610142919061025c565b60405180910390f35b6101536101a6565b6040516101609190610228565b60405180910390f35b6101716101ab565b60405161017e9190610228565b60405180910390f35b60d081565b600081565b60ff81565b600181565b60fe81565b61c35081565b600281565b600381565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006101db826101b0565b9050919050565b6101eb816101d0565b82525050565b600060208201905061020660008301846101e2565b92915050565b600060ff82169050919050565b6102228161020c565b82525050565b600060208201905061023d6000830184610219565b92915050565b6000819050919050565b61025681610243565b82525050565b6000602082019050610271600083018461024d565b9291505056fea2646970667358221220e18833793374082c3a7434762c168a8bca443098cc2772869640bdfd184b61fc64736f6c63430008180033";

type NilConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: NilConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Nil__factory extends ContractFactory {
  constructor(...args: NilConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Nil & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Nil__factory {
    return super.connect(runner) as Nil__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): NilInterface {
    return new Interface(_abi) as NilInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Nil {
    return new Contract(address, _abi, runner) as unknown as Nil;
  }
}
