/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type { Nil, NilInterface } from "../../../nil/Nil.sol/Nil";

const _abi = [
  {
    inputs: [],
    name: "FORWARD_NONE",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "FORWARD_PERCENTAGE",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "FORWARD_REMAINING",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "FORWARD_VALUE",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "IS_INTERNAL_MESSAGE",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MINT_CURRENCY",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "VERIFY_SIGNATURE",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x61024a610053600b82828239805160001a607314610046577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106100875760003560e01c8063a167fd5f11610065578063a167fd5f146100e6578063d2ec13b214610104578063df09b8eb14610122578063f58239571461014057610087565b806342e6d4d71461008c5780637f0a921b146100aa5780639bc465a0146100c8575b600080fd5b61009461015e565b6040516100a1919061019d565b60405180910390f35b6100b2610163565b6040516100bf91906101f9565b60405180910390f35b6100d0610168565b6040516100dd919061019d565b60405180910390f35b6100ee61016d565b6040516100fb91906101f9565b60405180910390f35b61010c610172565b604051610119919061019d565b60405180910390f35b61012a610177565b604051610137919061019d565b60405180910390f35b61014861017c565b60405161015591906101f9565b60405180910390f35b600081565b60ff81565b600181565b60fe81565b600281565b600381565b60d081565b600060ff82169050919050565b61019781610181565b82525050565b60006020820190506101b2600083018461018e565b92915050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006101e3826101b8565b9050919050565b6101f3816101d8565b82525050565b600060208201905061020e60008301846101ea565b9291505056fea2646970667358221220317e7219f15aac09e46a4776df0fbe48c955e6360496a233ccfc650214813eac64736f6c63430008180033";

type NilConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: NilConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Nil__factory extends ContractFactory {
  constructor(...args: NilConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Nil & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Nil__factory {
    return super.connect(runner) as Nil__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): NilInterface {
    return new Interface(_abi) as NilInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Nil {
    return new Contract(address, _abi, runner) as unknown as Nil;
  }
}
