/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Nil {
  export type TokenStruct = { id: BigNumberish; amount: BigNumberish };

  export type TokenStructOutput = [id: bigint, amount: bigint] & {
    id: bigint;
    amount: bigint;
  };
}

export interface WalletInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "asyncCall"
      | "bounce"
      | "getCurrencyBalanceOf"
      | "getCurrencyId"
      | "getCurrencyName"
      | "getCurrencyTotalSupply"
      | "getOwnCurrencyBalance"
      | "mintCurrency"
      | "send"
      | "sendCurrency"
      | "setCurrencyName"
      | "syncCall"
      | "verifyExternal"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "asyncCall",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      boolean,
      Nil.TokenStruct[],
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "bounce", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getCurrencyBalanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrencyId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrencyName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrencyTotalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnCurrencyBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintCurrency",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "send", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "sendCurrency",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCurrencyName",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "syncCall",
    values: [AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyExternal",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "asyncCall", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bounce", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCurrencyBalanceOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrencyId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrencyName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrencyTotalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnCurrencyBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintCurrency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "send", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sendCurrency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCurrencyName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "syncCall", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyExternal",
    data: BytesLike
  ): Result;
}

export interface Wallet extends BaseContract {
  connect(runner?: ContractRunner | null): Wallet;
  waitForDeployment(): Promise<this>;

  interface: WalletInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  asyncCall: TypedContractMethod<
    [
      dst: AddressLike,
      refundTo: AddressLike,
      bounceTo: AddressLike,
      feeCredit: BigNumberish,
      deploy: boolean,
      tokens: Nil.TokenStruct[],
      value: BigNumberish,
      callData: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  bounce: TypedContractMethod<[err: string], [void], "payable">;

  getCurrencyBalanceOf: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  getCurrencyId: TypedContractMethod<[], [bigint], "view">;

  getCurrencyName: TypedContractMethod<[], [string], "view">;

  getCurrencyTotalSupply: TypedContractMethod<[], [bigint], "view">;

  getOwnCurrencyBalance: TypedContractMethod<[], [bigint], "view">;

  mintCurrency: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  send: TypedContractMethod<[message: BytesLike], [void], "nonpayable">;

  sendCurrency: TypedContractMethod<
    [to: AddressLike, currencyId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setCurrencyName: TypedContractMethod<[name: string], [void], "nonpayable">;

  syncCall: TypedContractMethod<
    [
      dst: AddressLike,
      feeCredit: BigNumberish,
      value: BigNumberish,
      call_data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  verifyExternal: TypedContractMethod<
    [hash: BigNumberish, signature: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "asyncCall"
  ): TypedContractMethod<
    [
      dst: AddressLike,
      refundTo: AddressLike,
      bounceTo: AddressLike,
      feeCredit: BigNumberish,
      deploy: boolean,
      tokens: Nil.TokenStruct[],
      value: BigNumberish,
      callData: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bounce"
  ): TypedContractMethod<[err: string], [void], "payable">;
  getFunction(
    nameOrSignature: "getCurrencyBalanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCurrencyId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCurrencyName"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getCurrencyTotalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getOwnCurrencyBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "mintCurrency"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "send"
  ): TypedContractMethod<[message: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sendCurrency"
  ): TypedContractMethod<
    [to: AddressLike, currencyId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCurrencyName"
  ): TypedContractMethod<[name: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "syncCall"
  ): TypedContractMethod<
    [
      dst: AddressLike,
      feeCredit: BigNumberish,
      value: BigNumberish,
      call_data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyExternal"
  ): TypedContractMethod<
    [hash: BigNumberish, signature: BytesLike],
    [boolean],
    "view"
  >;

  filters: {};
}
