/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nilSol from "./Nil.sol";
export type { nilSol };
export type { NilCurrencyBase } from "./NilCurrencyBase";
