/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface BondingCurveBasicInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buy"
      | "calculateCurvedBurnReturn"
      | "calculateCurvedMintReturn"
      | "calculatePurchaseReturn"
      | "calculateSaleReturn"
      | "decimals"
      | "getCurrencyBalanceOf"
      | "getCurrencyId"
      | "getCurrencyName"
      | "getCurrencyTotalSupply"
      | "getOwnCurrencyBalance"
      | "mintCurrency"
      | "sell"
      | "sendCurrency"
      | "setCurrencyName"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "buy", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "calculateCurvedBurnReturn",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateCurvedMintReturn",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePurchaseReturn",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateSaleReturn",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCurrencyBalanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrencyId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrencyName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrencyTotalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnCurrencyBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintCurrency",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sell",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sendCurrency",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCurrencyName",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateCurvedBurnReturn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateCurvedMintReturn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculatePurchaseReturn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateSaleReturn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCurrencyBalanceOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrencyId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrencyName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrencyTotalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnCurrencyBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintCurrency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sell", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sendCurrency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCurrencyName",
    data: BytesLike
  ): Result;
}

export interface BondingCurveBasic extends BaseContract {
  connect(runner?: ContractRunner | null): BondingCurveBasic;
  waitForDeployment(): Promise<this>;

  interface: BondingCurveBasicInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buy: TypedContractMethod<[_destination: AddressLike], [void], "payable">;

  calculateCurvedBurnReturn: TypedContractMethod<
    [_amount: BigNumberish],
    [bigint],
    "view"
  >;

  calculateCurvedMintReturn: TypedContractMethod<
    [_amount: BigNumberish],
    [bigint],
    "view"
  >;

  calculatePurchaseReturn: TypedContractMethod<
    [
      _totalSupply: BigNumberish,
      _poolBalance: BigNumberish,
      _amount: BigNumberish
    ],
    [bigint],
    "view"
  >;

  calculateSaleReturn: TypedContractMethod<
    [
      _totalSupply: BigNumberish,
      _poolBalance: BigNumberish,
      _amount: BigNumberish
    ],
    [bigint],
    "view"
  >;

  decimals: TypedContractMethod<[], [bigint], "view">;

  getCurrencyBalanceOf: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  getCurrencyId: TypedContractMethod<[], [bigint], "view">;

  getCurrencyName: TypedContractMethod<[], [string], "view">;

  getCurrencyTotalSupply: TypedContractMethod<[], [bigint], "view">;

  getOwnCurrencyBalance: TypedContractMethod<[], [bigint], "view">;

  mintCurrency: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  sell: TypedContractMethod<
    [_amount: BigNumberish, _destination: AddressLike],
    [void],
    "payable"
  >;

  sendCurrency: TypedContractMethod<
    [to: AddressLike, currencyId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setCurrencyName: TypedContractMethod<[name: string], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<[_destination: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "calculateCurvedBurnReturn"
  ): TypedContractMethod<[_amount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateCurvedMintReturn"
  ): TypedContractMethod<[_amount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculatePurchaseReturn"
  ): TypedContractMethod<
    [
      _totalSupply: BigNumberish,
      _poolBalance: BigNumberish,
      _amount: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateSaleReturn"
  ): TypedContractMethod<
    [
      _totalSupply: BigNumberish,
      _poolBalance: BigNumberish,
      _amount: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCurrencyBalanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCurrencyId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCurrencyName"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getCurrencyTotalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getOwnCurrencyBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "mintCurrency"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sell"
  ): TypedContractMethod<
    [_amount: BigNumberish, _destination: AddressLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "sendCurrency"
  ): TypedContractMethod<
    [to: AddressLike, currencyId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCurrencyName"
  ): TypedContractMethod<[name: string], [void], "nonpayable">;

  filters: {};
}
