/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "__Precompile__",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.__Precompile____factory>;
    getContractFactory(
      name: "Nil",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Nil__factory>;
    getContractFactory(
      name: "NilBounceable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.NilBounceable__factory>;
    getContractFactory(
      name: "NilConfigAbi",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.NilConfigAbi__factory>;
    getContractFactory(
      name: "NilCurrencyBase",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.NilCurrencyBase__factory>;
    getContractFactory(
      name: "BondingCurveBasic",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BondingCurveBasic__factory>;

    getContractAt(
      name: "__Precompile__",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.__Precompile__>;
    getContractAt(
      name: "Nil",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Nil>;
    getContractAt(
      name: "NilBounceable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.NilBounceable>;
    getContractAt(
      name: "NilConfigAbi",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.NilConfigAbi>;
    getContractAt(
      name: "NilCurrencyBase",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.NilCurrencyBase>;
    getContractAt(
      name: "BondingCurveBasic",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BondingCurveBasic>;

    deployContract(
      name: "__Precompile__",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.__Precompile__>;
    deployContract(
      name: "Nil",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Nil>;
    deployContract(
      name: "NilBounceable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.NilBounceable>;
    deployContract(
      name: "NilConfigAbi",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.NilConfigAbi>;
    deployContract(
      name: "NilCurrencyBase",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.NilCurrencyBase>;
    deployContract(
      name: "BondingCurveBasic",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BondingCurveBasic>;

    deployContract(
      name: "__Precompile__",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.__Precompile__>;
    deployContract(
      name: "Nil",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Nil>;
    deployContract(
      name: "NilBounceable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.NilBounceable>;
    deployContract(
      name: "NilConfigAbi",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.NilConfigAbi>;
    deployContract(
      name: "NilCurrencyBase",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.NilCurrencyBase>;
    deployContract(
      name: "BondingCurveBasic",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BondingCurveBasic>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
